sonar.projectName=NexTime Mobile
sonar.projectKey=l02-bugfree_frontend
sonar.organization=l02-bugfree

# Trỏ nguồn và test vào thư mục mobile
sonar.sources=mobile
sonar.tests=mobile
sonar.test.inclusions=mobile/**/*.test.tsx,mobile/**/*.test.ts

# Đường dẫn report tính từ gốc dự án
sonar.javascript.lcov.reportPaths=mobile/coverage/lcov.info

# Exclusions cập nhật đường dẫn mới
sonar.exclusions=mobile/node_modules/**,mobile/coverage/**,mobile/test-report/**,mobile/__mocks__/**,mobile/HomeScreen.tsx,mobile/App.tsx,mobile/index.ts,mobile/GlobalStyles.ts
sonar.coverage.exclusions=mobile/HomeScreen.tsx,mobile/App.tsx,mobile/index.ts,mobile/**/*.test.tsx,mobile/**/*.test.ts
sonar.cpd.exclusions=mobile/HomeScreen.tsx
