sonar.projectName=NexTime Mobile
sonar.projectKey=l02-bugfree_frontend
sonar.organization=l02-bugfree
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Loại bỏ hoàn toàn các file tự sinh hoặc không quan trọng khỏi mọi loại phân tích (Security, Quality, Coverage)
sonar.exclusions=node_modules/**,coverage/**,test-report/**,__mocks__/**,HomeScreen.tsx,App.tsx,index.ts,GlobalStyles.ts
sonar.coverage.exclusions=HomeScreen.tsx,App.tsx,index.ts,**/*.test.tsx,**/*.test.ts
sonar.cpd.exclusions=HomeScreen.tsx